package com.epam.finaltask.controller.command;

/**
 * This class contains constant string of command names
 */
public enum CommandName {
	LOGIN, REGISTRATION_USER, NO_SUCH_COMMAND, LOGOUT, GO_TO_REGISTRATION, BACK_TO_HOME_PAGE,
	CHANGE_LOCAL, GO_TO_ADD_COURSE,GO_TO_ADD_TASK, SHOW_USERS, CHOICE_TEACHER, ASSIGN_TEACHER,SHOW_COURSES,
	GO_TO_REGISTRATION_ON_COURSE, SHOW_MY_COURSES, SHOW_MY_COURSE,SHOW_TEACHERS,
	DELETE_USER, CHANGE_ROLE,DELETE_COURSE,GO_TO_CHANGE_COURSE,CHANGE_COURSE,
	ADD_COURSE, SHOW_MY_TASK, ADD_TASK,GO_TO_ADD_RESULT, ADD_RESULT, LEAVE_COURSE,SHOW_TEACHERS_COURSES, SHOW_RESPONSES,
	SHOW_COURSE, EXECUTE_TASK, GO_TO_EXECUTE_TASK
}
