package com.epam.finaltask.controller.command;

/**
 * This class contains constant string of command names
 */
public enum CommandName {
	LOGIN, REGISTRATION_USER, NO_SUCH_COMMAND, LOGOUT, GO_TO_REGISTRATION, BACK_TO_HOME_PAGE, CHANGE_LOCAL, GO_TO_ADD_COURSE, SHOW_USERS,
	GO_TO_ASSIGN_TEACHER, ASSIGN_TEACHER,SHOW_COURSES, GO_TO_REGISTRATION_ON_COURSE,REGISTRATION_ON_COURSE, SHOW_MY_COURSES, SHOW_MY_COURSE,
	CANCEL_REGISTRATION,DELETE_USER, CHANGE_ROLE, GO_TO_CHANGE_COURSE,ADD_COURSE, SHOW_MY_TASK, ADD_TASK, ADD_RESULT, SENT_RESPONSE, LEAVE_COURSE, SHOW_COURSE, EXECUTE_TASK, GO_TO_EXECUTE_TASK
}
